// flow-typed signature: 70d64a3be995f05ae08e2d69787ba62d
// flow-typed version: <<STUB>>/json-over-tcp_v^0.3.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-over-tcp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-over-tcp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-over-tcp/example/helloWorld' {
  declare module.exports: any;
}

declare module 'json-over-tcp/grunt' {
  declare module.exports: any;
}

declare module 'json-over-tcp/lib/protocol' {
  declare module.exports: any;
}

declare module 'json-over-tcp/lib/server' {
  declare module.exports: any;
}

declare module 'json-over-tcp/lib/socket' {
  declare module.exports: any;
}

declare module 'json-over-tcp/test/protocol_test' {
  declare module.exports: any;
}

declare module 'json-over-tcp/test/server_test' {
  declare module.exports: any;
}

declare module 'json-over-tcp/test/socket_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-over-tcp/example/helloWorld.js' {
  declare module.exports: $Exports<'json-over-tcp/example/helloWorld'>;
}
declare module 'json-over-tcp/grunt.js' {
  declare module.exports: $Exports<'json-over-tcp/grunt'>;
}
declare module 'json-over-tcp/index' {
  declare module.exports: $Exports<'json-over-tcp'>;
}
declare module 'json-over-tcp/index.js' {
  declare module.exports: $Exports<'json-over-tcp'>;
}
declare module 'json-over-tcp/lib/protocol.js' {
  declare module.exports: $Exports<'json-over-tcp/lib/protocol'>;
}
declare module 'json-over-tcp/lib/server.js' {
  declare module.exports: $Exports<'json-over-tcp/lib/server'>;
}
declare module 'json-over-tcp/lib/socket.js' {
  declare module.exports: $Exports<'json-over-tcp/lib/socket'>;
}
declare module 'json-over-tcp/test/protocol_test.js' {
  declare module.exports: $Exports<'json-over-tcp/test/protocol_test'>;
}
declare module 'json-over-tcp/test/server_test.js' {
  declare module.exports: $Exports<'json-over-tcp/test/server_test'>;
}
declare module 'json-over-tcp/test/socket_test.js' {
  declare module.exports: $Exports<'json-over-tcp/test/socket_test'>;
}
